# Site settings
title: RO!RS
email: info@roi.rs
description: 
# baseurl: "/" # the subpath of your site, e.g. /blog/
url: "https://roi.rs" # the base hostname & protocol for your site
gems:
  - jekyll-coffeescript
  - jekyll-assets
# Build settings
assets:
  compress:
    js: my_uglifier
markdown: kramdown
exclude: ['vendor', 'config', 'Gemfile', 'Gemfile.lock', '.ruby-version']