# Site settings
title: ROI-RS
email: info@roi.rs
description: 
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "https://roi.rs" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
exclude: ['vendor', 'config', 'Gemfile', 'Gemfile.lock', '.ruby-version']